import React, {useEffect, useMemo, useState} from 'react';
import {Search, RotateCcw, Download, X, HelpCircle, ChevronLeft, ChevronRight, FileSearch, Settings} from 'lucide-react';
import {downloadWorkbook} from './overtimeWorkbook';
import OvertimeDateRange from './OvertimeDateRange';

type Row={id:string;customerOrder:string;fbaOrder:string;customer:string;channel:string;transport:string;delivery:string;country:string;warehouse:string;promised:number;actual:number;interval:string;start:string;end:string;signed:string;sales:string;operator:string};
export const overtimeRows:Row[] = [
 ['HD2608181063','深圳天图电子有限公司','美线海卡','ONT8',18,27,'2026-08-18','2026-09-14','2026-09-16','张伟','李晓'],
 ['HD2608191099','付豪跨境电商事业群','英线海卡','BHX4',25,32,'2026-08-12','2026-09-13','2026-09-15','陈晨','王敏'],
 ['HD2608202231','常晟供应链集团','美线海卡','GYR3',18,24,'2026-08-21','2026-09-14','2026-09-17','刘洋','李晓'],
 ['HD2608213345','深圳星链家居出口部','美线海卡','SBD1',18,22,'2026-08-25','2026-09-16','2026-09-18','张伟','赵静'],
 ['HD2608224412','上海豪迅美中快递中心','美线空派','',7,11,'2026-09-03','2026-09-14','2026-09-16','陈晨','王敏'],
 ['HD2608238812','常晟供应链集团','德线空派','FRA3',8,10,'2026-09-05','2026-09-15','2026-09-17','刘洋','赵静'],
].map(([id,customer,channel,warehouse,promised,actual,start,end,signed,sales,operator],index)=>({id:String(id),customerOrder:`CUS202608${String(18+index)}${String(1063+index*137)}`,fbaOrder:['FBA19G6M4C7B','FBA19G6N5Y1Z','FBA21KK9D12W','FBA19X8B7C9D','FBA19K7C5W2Y','FBA24M9V1K3S'][index],customer:String(customer),channel:String(channel),transport:String(channel).includes('空')?'空运':'海运',delivery:String(channel).includes('空')?'快递派送':'卡车派送',country:String(channel).startsWith('英')?'英国':String(channel).startsWith('德')?'德国':'美国',warehouse:String(warehouse),promised:Number(promised),actual:Number(actual),interval:String(channel).includes('空')?'起飞→入仓':'开船→入仓',start:start+' 09:00:00',end:end+' 09:00:00',signed:signed+' 15:30:00',sales:String(sales),operator:String(operator)}));
const headers=['运单号','客户单号','FBA单号','客户名称','服务','运输方式','尾程派送','国家','仓库代码','承诺时效','实际时效','超时天数','监控区间','起始时间','结束时间','签收时间','业务代表','跟单代表'];
const values=(r:Row)=>[r.id,r.customerOrder,r.fbaOrder,r.customer,r.channel,r.transport,r.delivery,r.country,r.warehouse,`${r.promised}天`,`${r.actual}天`,`${r.actual-r.promised}天`,r.interval,r.start,r.end,r.signed,r.sales,r.operator];
const empty={ids:'',customerOrder:'',fbaOrder:'',customer:'',channel:'',transport:'',delivery:'',min:'',max:'',from:'',to:'',startFrom:'',startTo:'',endFrom:'',endTo:''};
const rule='实际时效超过承诺时效1天以上时判定超时；超时天数为实际时效与承诺时效的差值。';
const input='h-8 min-w-0 w-full rounded border border-slate-200 bg-white px-2.5 text-xs outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-50';
const matchesBatch=(query:string,value:string)=>{const terms=query.trim().split(/[\s,，;；]+/).filter(Boolean);return !terms.length||terms.includes(value);};
export default function OvertimeWaybillsPage(){
 const [draft,setDraft]=useState(empty),[filters,setFilters]=useState(empty),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [settingsOpen,setSettingsOpen]=useState(false),[hiddenColumns,setHiddenColumns]=useState<string[]>([]),[draftHidden,setDraftHidden]=useState<string[]>([]);
 const [selected,setSelected]=useState<string[]>([]),[page,setPage]=useState(1),[size,setSize]=useState(10),[detail,setDetail]=useState<Row|null>(null);
 useEffect(()=>{if(!detail)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setDetail(null);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[detail]);
 const rows=useMemo(()=>{const ids=filters.ids.trim().split(/[\s,，;；]+/).filter(Boolean);return overtimeRows.filter(r=>r.actual>r.promised+1&&(!ids.length||ids.includes(r.id))&&matchesBatch(filters.customerOrder,r.customerOrder)&&matchesBatch(filters.fbaOrder,r.fbaOrder)&&(!filters.customer||r.customer===filters.customer)&&(!filters.channel||r.channel===filters.channel)&&(!filters.transport||r.transport===filters.transport)&&(!filters.delivery||r.delivery===filters.delivery)&&(!filters.min||r.actual-r.promised>=Number(filters.min))&&(!filters.max||r.actual-r.promised<=Number(filters.max))&&(!filters.startFrom||r.start>=filters.startFrom)&&(!filters.startTo||r.start<=filters.startTo)&&(!filters.endFrom||r.end>=filters.endFrom)&&(!filters.endTo||r.end<=filters.endTo)&&(!filters.from||r.signed>=filters.from)&&(!filters.to||r.signed<=filters.to)).sort((a,b)=>(b.actual-b.promised)-(a.actual-a.promised)||b.signed.localeCompare(a.signed));},[filters]);
 const pages=Math.max(1,Math.ceil(rows.length/size)),visible=rows.slice((page-1)*size,page*size);
 const change=(key:keyof typeof empty,value:string)=>setDraft(s=>({...s,[key]:value}));
 const query=(e:React.FormEvent)=>{e.preventDefault();if(draft.min!==''&&draft.max!==''&&Number(draft.min)>Number(draft.max)){setError('最小天数不能大于最大天数');return;}if(draft.from&&draft.to&&draft.from>draft.to){setError('签收时间：开始日期不能晚于结束日期');return;}if(draft.startFrom&&draft.startTo&&draft.startFrom>draft.startTo){setError('起始时间：开始日期不能晚于结束日期');return;}if(draft.endFrom&&draft.endTo&&draft.endFrom>draft.endTo){setError('结束时间：开始日期不能晚于结束日期');return;}setError('');setFilters({...draft});setPage(1);setSelected([]);setNotice('');};
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const exportRows=()=>{const records=selected.length?rows.filter(r=>selected.includes(r.id)):rows;const d=new Date();downloadWorkbook(headers,records.map(values),`超时运单_${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}.xlsx`);setNotice(`已导出 ${records.length} 条运单`);};
 return <main className="flex min-h-0 flex-1 flex-col gap-3 overflow-auto bg-[#f3f6fa] p-4 text-slate-700">
  <div className="flex items-center gap-2 py-1"><span className="h-4 w-1 rounded bg-blue-700"/><h1 className="text-sm font-semibold">运单时效监控</h1></div>
  <form onSubmit={query} className="rounded border border-slate-200 bg-white p-4 shadow-sm">
   <div className="grid grid-cols-1 gap-x-6 gap-y-4 xl:grid-cols-3 md:grid-cols-2">
    <label className="flex items-center gap-3 text-xs"><span className="w-16 shrink-0">运单号</span><textarea aria-label="运单号" className={input+' resize-y py-1.5'} placeholder="单个或批量输入，逗号 / 空格 / 换行分隔" value={draft.ids} onChange={e=>change('ids',e.target.value)}/></label>
    {([['customerOrder','客户单号'],['fbaOrder','FBA单号']] as const).map(([key,label])=><label key={key} className="flex items-center gap-3 text-xs"><span className="w-16 shrink-0">{label}</span><textarea aria-label={label} className={input+' resize-y py-1.5'} placeholder="单个或批量输入，逗号 / 空格 / 换行分隔" value={draft[key]} onChange={e=>change(key,e.target.value)}/></label>)}
    {(['customer','channel','transport','delivery'] as const).map((key,i)=><label key={key} className="flex items-center gap-3 text-xs"><span className="w-16 shrink-0">{['客户名称','服务','运输方式','尾程派送'][i]}</span><input className={input} list={`overtime-${key}`} placeholder="输入搜索或选择" value={draft[key]} onChange={e=>change(key,e.target.value)}/><datalist id={`overtime-${key}`}>{[...new Set(overtimeRows.map(r=>r[key]))].map(v=><option key={v} value={v}/>)}</datalist></label>)}
    <label className="flex items-center gap-3 text-xs"><span className="w-16 shrink-0">超时天数</span><input aria-label="最小天数" type="number" min="0" step="any" className={input} placeholder="最小天数" value={draft.min} onChange={e=>change('min',e.target.value)}/><span>～</span><input aria-label="最大天数" type="number" min="0" step="any" className={input} placeholder="最大天数" value={draft.max} onChange={e=>change('max',e.target.value)}/><span>天</span></label>
    <OvertimeDateRange label="签收时间" from={draft.from} to={draft.to} onChange={(from,to)=>setDraft(s=>({...s,from,to}))}/>
    <OvertimeDateRange label="起始时间" from={draft.startFrom} to={draft.startTo} onChange={(startFrom,startTo)=>setDraft(s=>({...s,startFrom,startTo}))}/>
    <OvertimeDateRange label="结束时间" from={draft.endFrom} to={draft.endTo} onChange={(endFrom,endTo)=>setDraft(s=>({...s,endFrom,endTo}))}/>
    <div className="flex items-center justify-end gap-2"><button className="flex h-8 items-center gap-1.5 rounded bg-[#0752b5] px-6 text-xs text-white hover:bg-blue-800"><Search size={13}/>查询</button><button type="button" onClick={()=>{setDraft(empty);setFilters(empty);setError('');setSelected([]);setPage(1);setNotice('');}} className="flex h-8 items-center gap-1.5 rounded border border-slate-200 px-6 text-xs hover:bg-slate-50"><RotateCcw size={13}/>重置</button></div>
   </div>{error&&<p role="alert" className="mt-3 text-xs text-red-600">{error}</p>}
  </form>
  <section className="flex min-h-[400px] flex-1 flex-col rounded border border-slate-200 bg-white shadow-sm">
   <div className="flex h-14 shrink-0 items-center justify-between px-4"><div className="flex items-center gap-4 text-xs"><button disabled={!rows.length} onClick={exportRows} className="flex h-8 items-center gap-1.5 rounded bg-[#0752b5] px-4 text-xs text-white disabled:opacity-40"><Download size={13}/>导出</button>{selected.length>0&&<span className="text-blue-700">已选择 {selected.length} 条 <button onClick={()=>setSelected([])} className="ml-2 underline">清空</button></span>}<span role="status" className="text-slate-500">{notice}</span></div><button aria-label="列表设置" title="列表设置" onClick={()=>{setDraftHidden([...hiddenColumns]);setSettingsOpen(true);}} className="flex h-8 w-9 items-center justify-center rounded bg-[#0752b5] text-white hover:bg-blue-800"><Settings size={15}/></button></div>
   <div className="min-h-0 flex-1 overflow-auto"><table style={{minWidth:Math.max(900,2280-hiddenColumns.length*130)}} className="w-full border-collapse text-left text-xs"><thead className="sticky top-0 z-20 bg-[#f6f8fb] text-slate-600"><tr><th className="sticky left-0 w-10 bg-[#f6f8fb] p-3"><input aria-label="选择本页全部运单" type="checkbox" checked={visible.length>0&&visible.every(r=>selected.includes(r.id))} ref={el=>{if(el)el.indeterminate=visible.some(r=>selected.includes(r.id))&&!visible.every(r=>selected.includes(r.id));}} onChange={e=>setSelected(s=>e.target.checked?[...new Set([...s,...visible.map(r=>r.id)])]:s.filter(id=>!visible.some(r=>r.id===id)))}/></th>{headers.map((h,i)=>hiddenColumns.includes(h)?null:<th key={h} className={`whitespace-nowrap border-y border-r border-slate-200 px-3 py-3 font-medium ${i===0?'sticky left-10 bg-[#f6f8fb]':''}`}><span className="inline-flex items-center gap-1">{h}{headers[i]==='超时天数'&&<span tabIndex={0} title={rule} aria-label={rule}><HelpCircle size={13}/></span>}</span></th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.id} className={`group ${selected.includes(r.id)?'bg-blue-50':'bg-white'} hover:bg-blue-50/60`}><td className="sticky left-0 border-b border-slate-100 bg-inherit p-3"><input type="checkbox" aria-label={`选择 ${r.id}`} checked={selected.includes(r.id)} onChange={()=>toggle(r.id)}/></td>{values(r).map((v,i)=>hiddenColumns.includes(headers[i])?null:<td key={i} className={`whitespace-nowrap border-b border-r border-slate-100 px-3 py-4 ${i===0?'sticky left-10 bg-inherit':''} ${headers[i]==='超时天数'?'font-semibold text-red-600 tabular-nums':''}`}>{i===0?<button className="font-medium text-blue-700 hover:underline" onClick={()=>setDetail(r)}>{v}</button>:v}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="flex flex-col items-center gap-3 py-24 text-sm text-slate-400"><FileSearch size={36} strokeWidth={1.2}/>暂无符合条件的超时运单</div>}</div>
   <footer className="flex h-14 shrink-0 items-center justify-end gap-4 border-t border-slate-200 px-4 text-xs"><span>共 {rows.length} 条</span><select aria-label="每页条数" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1);}} className="rounded border border-slate-200 p-1.5">{[3,5,10,20].map(n=><option key={n} value={n}>{n}条/页</option>)}</select><button aria-label="上一页" disabled={page===1} onClick={()=>setPage(p=>p-1)} className="disabled:opacity-30"><ChevronLeft size={16}/></button>{Array.from({length:pages},(_,i)=><button key={i} onClick={()=>setPage(i+1)} className={`h-7 w-7 rounded ${page===i+1?'bg-blue-700 text-white':'hover:bg-slate-100'}`}>{i+1}</button>)}<button aria-label="下一页" disabled={page===pages} onClick={()=>setPage(p=>p+1)} className="disabled:opacity-30"><ChevronRight size={16}/></button></footer>
  </section>
  {settingsOpen&&<div className="fixed inset-0 z-50 flex justify-end bg-black/35" onClick={()=>setSettingsOpen(false)}><section role="dialog" aria-modal="true" aria-label="列表设置" className="flex h-full w-[420px] max-w-full flex-col bg-white shadow-xl" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setSettingsOpen(false);}}><header className="flex items-center justify-between border-b p-5"><h2 className="text-sm font-semibold">列表设置</h2><button autoFocus aria-label="关闭设置" onClick={()=>setSettingsOpen(false)}><X size={18}/></button></header><div className="flex-1 overflow-auto p-5"><h3 className="mb-2 text-sm font-medium">显示字段</h3><p className="mb-5 text-xs text-slate-400">勾选需要显示的字段，运单号固定显示。</p><div className="grid grid-cols-2 gap-4">{headers.map((h,i)=><label key={h} className="flex items-center gap-2 text-xs"><input type="checkbox" disabled={i===0} checked={!draftHidden.includes(h)} onChange={e=>setDraftHidden(s=>e.target.checked?s.filter(v=>v!==h):[...s,h])}/>{h}</label>)}</div></div><footer className="flex justify-between border-t p-4"><button onClick={()=>setDraftHidden([])} className="text-xs text-blue-600">恢复默认</button><div className="flex gap-2"><button onClick={()=>setSettingsOpen(false)} className="rounded border px-4 py-2 text-xs">取消</button><button onClick={()=>{setHiddenColumns(draftHidden);setSettingsOpen(false);}} className="rounded bg-[#0752b5] px-4 py-2 text-xs text-white">保存</button></div></footer></section></div>}
  {detail&&<div className="fixed inset-0 z-50 flex justify-end bg-black/35" onClick={()=>setDetail(null)}><section role="dialog" aria-modal="true" aria-label="运单详情" className="flex h-full w-[680px] max-w-full flex-col bg-white shadow-xl" onClick={e=>e.stopPropagation()}><header className="flex items-center justify-between border-b p-5"><h2 className="font-semibold">运单详情 · {detail.id}</h2><button autoFocus aria-label="关闭详情" onClick={()=>setDetail(null)}><X size={20}/></button></header><div className="flex-1 overflow-auto p-6"><h3 className="mb-4 border-l-4 border-blue-700 pl-2 text-sm font-semibold">基本信息与时效</h3><dl className="grid grid-cols-2 gap-x-6">{headers.map((h,i)=><div key={h} className="border-b border-slate-100 py-4"><dt className="mb-2 text-xs text-slate-400">{h}</dt><dd className={`text-sm ${headers[i]==='超时天数'?'font-semibold text-red-600':''}`}>{values(detail)[i]||'—'}</dd></div>)}</dl><p className="mt-6 rounded bg-slate-50 p-3 text-xs leading-6 text-slate-500">{rule}</p></div><footer className="border-t p-4 text-right"><button className="rounded border px-5 py-2 text-xs" onClick={()=>setDetail(null)}>关闭</button></footer></section></div>}
 </main>;
}
